
services:

  inventory:
    git_url: git@github.com:trevor-ofarrell/signal-labs-nodejs-coding-challenege
    git_branch: master
    command: npm start
    build_root: .
    ports:
      - container: 3000
        http: 80
        https: 443
    env_vars:
      NODE_ENV: production 